### ISSUE TITLE
アプリランチャ画面にアイコンを並べるデザイン

### ISSUE THREAD

**Issue by shimono** [fujitsu-pio/home-app#1]
アプリランチャ画面にアイコンを並べるHTMLのひな形を実装する

**Comment by dixonsiu** [comment]
具体的説明できますでしょうか？
改善のコメントの場合、できれば、現在・期待を記載してください。

**Comment by shimono** [comment]
ごめんなさい、過去のIssueですでに解決しているのでクローズします。
