### ISSUE TITLE
ミニマムアプリの実装

### ISSUE THREAD

**Issue by shimono** [fujitsu-pio/home-app#3]
ミニマムアプリを実装してインストールできるようにする

**Comment by dixonsiu** [comment]
Here is what I understood.  
1. box-resources must be zipped as bar file and installed onto the user's cell  
    1. access appcell-resources through internet
1. appcell-resources is hosted on another web server or common cell

**Comment by dixonsiu** [comment]
The following commits provide box installation feature of HomeApp.
1. Commit 3642de3d8e3d42944055ac87f314658e0dad7e80
1. Commit 9225002c107eba7dd1b04d0cf9435ccc7f41edbf
